### ISSUE TITLE
Maintenance of ventilation value

### ISSUE THREAD

**Issue by driagi** [EnzoD86/tuya-smart-ir-ac#27]
When you switch from Hot/Cold to Off,  it maintains the ventilation value (high, low, medium). When you switch from off to hot/cold, ventilation returns to Auto. 
I believe (personal opinion), it would be better to maintain the previous ventilation value.

**Comment by EnzoD86** [comment]
Hi, ~~I confirm that the current operating mode is as you described.~~
~~The fan speed is reset when you change the HVAC mode (auto/cold/hot/fan/dry mode).~~
~~This way of working is used to try to make the integration compatible with all (or most) existing air conditioners.~~
~~This is because I have noticed, from my experience and from other users' reports, that some air conditioner models do not allow switching to a specific mode unless the fan is first set to "auto".~~
~~I am pretty sure that this only applies to the dry mode, but I cannot be 100% sure.~~
~~Also, this is not always true, because some air conditioners need to set the fan to minimum when switching to dry mode (and this is why the integration implements some compatibility flags to be activated to solve these problems).
This explains the reason for the choice to always reset the fan speed to "auto" (except in cases where the compatibility option is enabled).~~
I recently implemented the ability to configure the default fan speed that is used for all modes except dry mode.
And you can do this by activating the "Default fan speed when setting HVAC mode" flag which activates an entity, where you can choose the default fan speed, which will be set when you change the HVAC mode.

I also want to point out that if the air conditioner is turned on without changing the HVAC mode, the fan is not reset.
Actually, the Home Assistant interface does not allow you to turn on the air conditioner without necessarily having to set a HVAC mode; but if you try to call the "climate.turn_on" action to turn on your air conditioner, you will notice that the air conditioner turns on using the previous mode and fan speed.
Example:
```
action: climate.turn_on
target:
  entity_id: climate.name_of_your_air_conditioner
```

After explaining the reasons for the choice and the possible workarounds that can be used, I might also find a way to keep the previous fan speed only in the cold and heat modes (which I think are the most used) and make this option configurable.
It won't be a high priority task but I'll try to look into it anyway.
Thanks for the suggestion.

**Comment by driagi** [comment]
Forgive me, I didn't understand where I can set  the default fan speed.

**Comment by EnzoD86** [comment]
You need to go to the Home Assistant settings, select the Tuya Smart IR AC integration and from the list of air conditioners you have configured click on the configure button.
The air conditioner configuration page will open (the same one you configured when you first inserted the air conditioner), going down you will find the "Default fan speed when setting HVAC mode" flag; activate it and confirm the changes.
Now among the entities exposed by your air conditioner, you should also see a combobox from which you can select the default fan speed.

**Comment by driagi** [comment]
Forgive me, but I don't see it
![image](https://github.com/user-attachments/assets/334ce0be-b925-44a6-8ff7-6eb9be8fb788)

**Comment by EnzoD86** [comment]
Very strange... can you try clearing your browser cache and/or opening the home assistant page in an incognito tab to see if that changes anything?

**Comment by driagi** [comment]
I tried incognito. I have the same screen. Same thing in APP.

![image](https://github.com/user-attachments/assets/8bcf6a88-6543-4036-a7b2-0ec603b26285)

**Comment by driagi** [comment]
Perdonami se rompo le balle.
Scrivo solo per contribuire nel migliorare il tuo fantastico lavoro.
Non pretendo soluzioni rapide nemmeno soluzioni in generale.

Già così mi hai fatto un ottimo servizio.

Il giorno ven 11 ott 2024 alle ore 09:21 EnzoD86 ***@***.***>
ha scritto:

**Comment by EnzoD86** [comment]
Non ti preoccupare, infatti sto cercando di capire come mai hai questo comportamento anomalo.
Se puoi/vuoi raggiungerci nel gruppo telegram dove posso darti una migliore assistenza e switchiamo in italiano:
https://t.me/+iHgzgJfY41BjMzU0

**Comment by driagi** [comment]
Fatto. Grazie

Il giorno ven 11 ott 2024 alle ore 09:42 EnzoD86 ***@***.***>
ha scritto:

**Comment by driagi** [comment]
Solved. My update error.

**Comment by EnzoD86** [comment]
Hi, after analyzing the code that manages the fan speed setting, I confirm that the integration already works like this.
The fan speed is maintained when the "Default fan speed when setting HVAC mode" option is disabled.
