### ISSUE TITLE
Sending command didn't update IR controller's states

### ISSUE THREAD

**Issue by lukechen0129** [EnzoD86/tuya-smart-ir-ac#28]
Whenever I switch on / off, set temperature, set fan speed from HomeAssistant. The IR controller with screen didn't update accordingly. Same issue happen on the other way around. When I set temperature via the IR controller, the state on HomeAssistant won't update accordingly.

**Comment by EnzoD86** [comment]
Hi, to try to help you, I need more information. 
Which model of ir hub are you using?
When you send a command to your air conditioner, does the data update on the Smart Life app? 
Thanks

**Comment by lukechen0129** [comment]
I am using the Momax air conditioner controller (SL11S), And the data on Smart Life app didn't update when i make changes from HomeAssistant. And If I make changes in the Smart Life app, the state in HomeAssistant didn't update. Also, thanks for making this repo, it helps me a lot.

**Comment by EnzoD86** [comment]
Sorry, but I'm still not clear... when you send commands from Smart Life, does the data update on the controller display?

**Comment by lukechen0129** [comment]
Yes it does. and it also appears in the debug logs on the tuya iot developer platform. 
But when I send command from HomeAssistant, the data update didn't appear in the debug log on tuya developer platform for the IR controller.

**Comment by EnzoD86** [comment]
are you sure that the data configured in the configuration.yaml file accesses your same smart life connected project that you are using?

**Comment by lukechen0129** [comment]
I believe so. Because I have only 1 project, plus the command sent from HA does create debug log for the air conditioner device, it just doesn't create any log for IR hub device.

**Comment by EnzoD86** [comment]
But when you send commands from Home Assistant, does the air conditioner execute the command?

**Comment by lukechen0129** [comment]
It does execute the command, at least the air con responded with a beep sound.

**Comment by EnzoD86** [comment]
it's very strange, evidently the Momax hub has a different way of working compared to normal ir hubs.
The strange thing is that if the air conditioner executes the command sent by home assistant, the command actually arrives to the server and to your configured cloud project which then sends it to your air conditioner via the ir hub (otherwise it wouldn't work, since the integration doesn't work locally).
I tried googling but I found little information about this hub.
I would like to be able to help you, but not having this hardware, I can't reproduce this scenario.

**Comment by EnzoD86** [comment]
Let's do this test; launch a command from the display of your IR HUB and then perform these operations:
- connect to the tuya platform site;
- go to the "api explorer" section;
- select "IR Control Hub Open service";
- select "Infrared Air Conditioner APIS",
- select "Get Air Conditioner Statuts";
- in the parameters enter "infrared_id" the hub id and "remote_id" the air conditioner id;
- click on "Submit Request";
- and look at the response; verify if the response you get shows you the same or different data than what your IR HUB screen shows you.

![image](https://github.com/user-attachments/assets/7b712d77-d07a-4e22-93c2-49702292a02a)

**Comment by lukechen0129** [comment]
Just tried and seems the response shows the temperature different from the hub
![image](https://github.com/user-attachments/assets/800d1be8-e2a1-47d1-b86b-cf219860d3fb)
This is what I found in the response, which matches what it shows in HA
![image](https://github.com/user-attachments/assets/b7fba3c2-ce4c-435e-adf8-461aef6b1903)
This is the debug log of the IR hub and this matches the IR HUB screen.

**Comment by lukechen0129** [comment]
Did some googling and realize my device looks identical with a device called `Moes Smart Infrared AC Controller - Model SD16Pro` and they share same `Product Category` which is `hwktwkq` in the device information.

**Comment by EnzoD86** [comment]
ok, this shows us that home assistant communicates correctly with the tuya open api, but evidently the hub uses a different system or different apis to update the data on the display...

I can't think of any solution to this problem at the moment.
Except that it's not possible to better understand where the hub gets the information that is displayed on the display

**Comment by lukechen0129** [comment]
Understand. Thanks anyway for trying to help. 🙏

**Comment by EnzoD86** [comment]
hi @lukechen0129 
I'm reopening this thread because I received [feedback ](https://github.com/EnzoD86/tuya-smart-ir-ac/issues/29#issuecomment-2445376186) from another user on a device very similar to yours.

In his case the model is precisely the [MOES Tuya WiFi Smart IR Thermostat AC Remote Controller Temperature and Humidity Sensor](https://moeshouse.com/products/wifi-ir-thermostat-with-ac-remote-and-sensor?srsltid=AfmBOopdVSF42HOq_nnWAS0VVbWDO9jO-bVKBX8l8W64PEzvT-lNFj8j) and it work with Home Assistant.
I hope this information can help you.
Bye
